### ISSUE TITLE
Doesn't work...

### ISSUE THREAD

**Issue by gelato** [sophicware/lita-salt#20]
Basically it doesn't work...
When i try to login i get no token.
When i try to say "salt up" i get: 

[2016-01-30 07:10:06 UTC] ERROR: Lita::Handlers::Salt crashed. The exception was:
undefined method `strip' for nil:NilClass

Lita wan't start until you remove ENV[""], leaving only "login/password"

Or mayby i did something wrong?

**Comment by jcockhren** [comment]
@gelato Hey. Given you don't have any info concerning your config, let me ask: 
1. How are you setting the authentication credentials?
2. Also, could you shed some light on what you meant by, `Lita wan't start until you remove ENV[""], leaving only "login/password"`?

**Comment by gelato** [comment]
Hey )
I'm setting auth credentials through config file:
Lita.configure do |config|
    config.handlers.salt.url = "http://localhost:5417"
    config.handlers.salt.username = "login"
    config.handlers.salt.password = "password"
end

Soo, when i try to set login/password as it is in your guide (config.handlers.salt.username = ENV["SALT_USERNAME"]) lita won't start with exception "Username must be set(or password)"

**Comment by gelato** [comment]
FATAL: Configuration attribute "username" is required for "salt" handler. - this, to be precise

**Comment by gelato** [comment]
Yeah, i looked a bit more in ruby syntax and figured that i had to set ENV variables somewhere first )
So i set them in that ruby config and it works now just like in your guide, but...
When i try "salt login" i get confirmation and then empty token string.
And if i run "salt up" i get this from ruby(Ruby 2.2 btw):

[2016-02-02 07:02:34 UTC] ERROR: Lita::Handlers::Salt crashed. The exception was:
undefined method `strip' for nil:NilClass
Full backtrace:
/usr/lib/ruby/2.2.0/net/http/header.rb:17:in`block in initialize_http_header'
/usr/lib/ruby/2.2.0/net/http/header.rb:15:in `each'
/usr/lib/ruby/2.2.0/net/http/header.rb:15:in`initialize_http_header'
/usr/lib/ruby/2.2.0/net/http/generic_request.rb:43:in `initialize'
/var/lib/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:62:in`new'
/var/lib/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:62:in `create_request'
/var/lib/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in`perform_request'
/var/lib/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
/var/lib/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in`with_net_http_connection'
/var/lib/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
/var/lib/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in`call'
/var/lib/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/var/lib/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in`run_request'
/var/lib/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
/var/lib/gems/2.2.0/gems/lita-salt-1.1.0/lib/lita/handlers/salt.rb:204:in`make_request'
/var/lib/gems/2.2.0/gems/lita-salt-1.1.0/lib/lita/handlers/salt.rb:117:in `manage_up'
/var/lib/gems/2.2.0/gems/lita-4.7.0/lib/lita/callback.rb:31:in`public_send'
/var/lib/gems/2.2.0/gems/lita-4.7.0/lib/lita/callback.rb:31:in `call'
/var/lib/gems/2.2.0/gems/lita-4.7.0/lib/lita/handler/chat_router.rb:97:in`dispatch_to_route'
/var/lib/gems/2.2.0/gems/lita-4.7.0/lib/lita/handler/chat_router.rb:82:in `block in dispatch'
/var/lib/gems/2.2.0/gems/lita-4.7.0/lib/lita/handler/chat_router.rb:72:in`map'
/var/lib/gems/2.2.0/gems/lita-4.7.0/lib/lita/handler/chat_router.rb:72:in `dispatch'
/var/lib/gems/2.2.0/gems/lita-4.7.0/lib/lita/robot.rb:69:in`block in receive'
/usr/lib/ruby/2.2.0/set.rb:283:in `each_key'
/usr/lib/ruby/2.2.0/set.rb:283:in`each'
/var/lib/gems/2.2.0/gems/lita-4.7.0/lib/lita/robot.rb:66:in `map'
/var/lib/gems/2.2.0/gems/lita-4.7.0/lib/lita/robot.rb:66:in`receive'
/var/lib/gems/2.2.0/gems/lita-slack-1.7.2/lib/lita/adapters/slack/message_handler.rb:119:in `dispatch_message'
/var/lib/gems/2.2.0/gems/lita-slack-1.7.2/lib/lita/adapters/slack/message_handler.rb:159:in`handle_message'
/var/lib/gems/2.2.0/gems/lita-slack-1.7.2/lib/lita/adapters/slack/message_handler.rb:18:in `handle'
/var/lib/gems/2.2.0/gems/lita-slack-1.7.2/lib/lita/adapters/slack/rtm_connection.rb:100:in`block in receive_message'
/var/lib/gems/2.2.0/gems/lita-slack-1.7.2/lib/lita/adapters/slack/event_loop.rb:10:in `block in defer'
/var/lib/gems/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:1067:in`call'
/var/lib/gems/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:1067:in `block in spawn_threadpool'

**Comment by jcockhren** [comment]
@gelato what version of lita bot are you using?

**Comment by jcockhren** [comment]
@gelato As of version 1.1, `salt login` is protected and will prompt you to confirm you're trying to run that command. Here's the flow (assuming from the shell adapter):

``` shell
Lita > salt login
This command requires confirmation. To confirm, send the command "confirm abcdef"
Lita > @lita confirm abcdef
login successful
token: kwklweklewklweklewlkewlkwe
Lita > salt up
```

As you can see, you won't be able to grab a new token unless you confirm with the one-time pass supplied.

**Comment by gelato** [comment]
@jcockhren i'm using lita 4.7.0, after i try to login (salt-api through cherrypy only on localhost, no ssl) through lita (adapter - slack, but it doesn't really matter) i get this:

litaBOT
9:27 AM login successful
token:

If i run "salt up" after this - i get the aforementioned error.

**Comment by jcockhren** [comment]
@gelato Thanks for the info.

I've spun up a clean version of lita (4.7.0) and it works for me without issue. Have you tried testing salt-api login via curl/httpie? I've tried the plugin against lita 4.7.0 and salt 2015.5.5 and it works smoothly from a clean setup. So far I haven't been able to reproduce on my side.

Which version of salt are you using? [2015.8.0 had a bug preventing authentication for Salt-api via a token](https://github.com/saltstack/salt/issues/27270)

**Comment by gelato** [comment]
@jcockhren i have 2015.8.4 (Beryllium) but the same error persisted on 2015.8.3
Login works okay - i can get token using curl through salt-api.
Why are you using such an old saltstack? 2015.8.4 is most recent one...

**Comment by jcockhren** [comment]
> Why are you using such an old saltstack? 2015.8.4 is most recent one...

There are usually critical regressions between major versions of saltstack. It's more than a pain to discover them after you've upgraded your entire infrastructure. It's safer to lag behind to watch the bug fixes/issues. 

In any case, I'll label this as a bug and test it against 2015.8.x

**Comment by gelato** [comment]
Thank you )

**Comment by gelato** [comment]
Sooo, any news...?

**Comment by jcockhren** [comment]
deprecating this repo
